apiVersion: apps/v1
kind: Deployment 
metadata:
  name: db-deployment
  labels:
    app: voting-app
    name: db-deployment

spec:
  selector:
    matchLabels:
      app: voting-app 
      name: db
  template:
    metadata:
      name: db
      labels:
        app: voting-app 
        name: db

    spec:
      containers:
        - name: db
          image: postgres:9.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
      - name: db-data
        emptyDir: {} 
  replicas: 1