apiVersion: apps/v1
kind: Deployment 
metadata:
  name: worker-deployment
  labels:
    app: voting-app
    name: worker-deployment

spec:
  selector:
    matchLabels:
      app: voting-app 
      name: worker-pod 
  template:
    metadata:
      name: worker-pod
      labels:
        app: voting-app 
        name: worker-pod 

    spec:
      containers:
        - name: worker-pod
          image: docker/example-voting-app-worker

  replicas: 2
        
