apiVersion: v1
kind: Service 
metadata:
  name: db-ts
  labels:
    app: voting-app
    name: db-ts

spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30006
  selector:
    app: voting-app 
    name: db