apiVersion: v1
kind: Service 
metadata:
  name: vote-service
  labels:
    app: voting-app
    name: vote-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app 
    name: vote-pod