apiVersion: v1
kind: Pod 
metadata:
  name: vote-pod
  labels:
    app: voting-app 
    name: vote-pod 

spec:
  containers:
    - name: vote-pod
      image: docker/example-voting-app-vote
      ports:
        - containerPort: 80